//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TMS_Launcher.rc
//
#define CREATEPROCESS_MANIFEST_RESOURCE_ID 1
#define RT_MANIFEST                     24
#define TMS_LAUNCHER_DIALOG             129
#define IDI_SYSTRAY_ICON                202
#define GENERAL_PAGE                    204
#define IDD_ABOUTBOX                    206
#define URLS_PAGE                       207
#define DEFECTS_PAGE                    208
#define IDD_MYOPTIONSHEET               209
#define TASKS_PAGE                      210
#define IDB_BITMAP1                     211
#define IDR_ACCELERATORS                212
#define URL_EDIT_PAGE                   213
#define DEFECT_EDIT_PAGE                214
#define SOFTTEST_PAGE                   216
#define HISTORY_PAGE                    217
#define IDC_TASKNAME                    1000
#define VIEW_TASK                       1001
#define IDC_EXPAND                      1002
#define VIEW_PARENT_TASK                1003
#define VIEW_CHILD_TASKS                1004
#define IDC_SETTINGS                    1005
#define IDC_CLOSE                       1006
#define VIEW_TASK_HOTKEY                1007
#define VIEW_CHILD_TASKS_HOTKEY         1008
#define IDC_EXPANDED                    1009
#define IDC_AUTORUN                     1010
#define IDC_USUAL_TMS                   1011
#define IDC_ALT_TMS                     1012
#define IDC_MINIMIZE                    1016
#define IDC_SINGLE_CLICK                1017
#define IDC_ABOUT                       1018
#define IDC_ABOUT_VERSION               1021
#define IDC_PAGE_CAPTION                1022
#define IDC_CLIENT_ID                   1024
#define IDC_DEFECT_NEW                  1025
#define IDC_DEFECT_EDIT                 1026
#define IDC_DEFECT_DELETE               1027
#define IDC_DEFECT_COPY                 1028
#define IDC_DEFECT_PROJECT              1029
#define IDC_MIN_CLIENT                  1030
#define IDC_CLIENT_ID2                  1030
#define IDC_MAX_CLIENT                  1031
#define IDC_MAX_ID                      1032
#define IDC_MIN_ID                      1033
#define IDC_MIN_EXT                     1034
#define IDC_BROWSER_PATH                1034
#define IDC_MAX_EXT                     1035
#define IDC_DEFECTS_LINK                1035
#define IDC_BROWSE                      1036
#define IDC_DEFECTS_LINK2               1036
#define IDC_LINK_NEW                    1037
#define IDC_DEFECTS_LINK3               1037
#define IDC_LINK_EDIT                   1038
#define IDC_LINK_SAVE                   1039
#define IDC_LINK_DELETE                 1040
#define IDC_URL_CAPTION                 1041
#define IDC_TASK_URL                    1042
#define IDC_URL_DEFAULT                 1043
#define IDC_CHILD_TASKS_URL             1044
#define IDC_URL_CAPTION2                1045
#define IDC_CLIENT_EDIT                 1046
#define IDC_URL_EDIT                    1047
#define IDC_SEPARATORS                  1048
#define IDC_TASKS_SEPARATORS            1050
#define IDC_DEFAULT_BROWSER             1052
#define IDC_CONTENTS                    1053
#define IDC_HELP_BUTTON                 1054
#define IDC_URLS_LIST                   1055
#define IDC_LINK_COPY                   1056
#define VIEW_PARENT_TASK_HOTKEY         1057
#define IDC_DEFECTS_LIST                1058
#define IDC_LOGIN                       1060
#define IDC_PASSWORD                    1061
#define IDC_TASKNAME_COMBO              1063
#define IDC_RIGHT_CLICK                 1064
#define IDC_TASK_NAME_CONTROL           1065
#define IDC_MAX_HISTORY                 1066
#define IDC_MAX_SPIN                    1068
#define IDC_SOFTTEST_PATH               1069
#define IDC_SOFTTEST_LOGIN              1070
#define IDC_SOFTTEST_PASSWORD           1071
#define IDC_SOFTTEST_BROWSE             1072
#define IDC_ST_DEFECTS                  1073
#define IDC_SOFTTEST_FILTER             1074
#define IDC_HISTORY_LIST                1075
#define IDC_BUTTON_DELETE               1076
#define IDC_BUTTON_CLEAR                1077
#define IDC_FILL_ID                     1078
#define IDC_COMPANY                     1079
#define IDC_COPYRIGHT                   1080
#define ID_MENU_UNDO                    32774
#define ID_MENU_CUT                     32775
#define ID_MENU_COPY                    32776
#define ID_MENU_PASTE                   32777
#define ID_MENU_DELETE                  32778
#define ID_MENU_SELECT                  32779
#define ID_CLEAR_HISTORY                32780
#define ID_SHOW_HIDE_WINDOW             32781
#define ID_SETTINGS_GENERAL             32782
#define ID_SETTINGS_URLS                32783
#define ID_SETTINGS_DEFECTS             32784
#define ID_SETTINGS_FORMAT              32785
#define ID_SETTINGS_SOFTTEST            32786
#define ID_SETTINGS_HISTORY             32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
